apiVersion: backstage.io/v1alpha1
relations:
  - target:
      kind: resource
      namespace: default
      name: catalog-dependent-service-b
    type: ownedBy
    source: something
kind: Resource
metadata:
  name: catalog-dependent-service-a
  description: Fake dependent service
spec:
  owner: dx
  type: service
  system: artist-engagement-portal
