apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: catalog-dependent-service-a
  description: Fake dependent service
spec:
  owner: dx
  type: service
  lifecycle: production
  dependsOn:
    - Component:default/catalog-dependent-service-b
  system: example
