apiVersion: backstage.io/v1alpha1
relations:
  - target:
      kind: resource
      namespace: default
      name: catalog-dependent-service-b
    type: dependsOn
    # This is not documented...
    source:
      kind: Resource
      name: catalog-dependent-service-a
kind: Resource
metadata:
  name: catalog-dependent-service-a
  description: Fake dependent service
spec:
  owner: dx
  type: service
  system: artist-engagement-portal
